### PR TITLE
fix failmsg@.service

### PR DESCRIPTION
**Pull request by you-oops-dev**

### CODE REVIEW

**Comment by you-oops-dev** [comment]
I fixed everything as you said

**Comment by dino-** [comment]
I got it from your earlier PR, I will be putting this and more changes into the main branch and pushing soon. Thanks!

**Comment by you-oops-dev** [comment]
That is, will you bring it in with your own hands?

**Comment by you-oops-dev** [comment]
Consider my proposal as well.
Instead of replace **| tai**l with the **-b** option.
What do you think?

**Comment by dino-** [comment]
I don't understand what you mean. The only `| tail` is in `failmsg.sh` line 27

`log=$(${journalctlPrefix} -u "$unitName" | tail)`

The `-b` switch for journalctl will show only since last boot and tail doesn't have a `-b`

What I want to happen here is only the last several lines (tail defaults to 10 lines) because these logs are sometimes very long for an email.

**Comment by you-oops-dev** [comment]
Well, with the `tail` command, you filter out only the end in the output, and at the end that the last start of the service is correct, or rather its output.

**Pull request closed without merging**
